# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
#    param_fetcher_listener:  true
#    allowed_methods_listener:  true
    routing_loader: true
    view:
        default_engine:       twig
        view_response_listener:  true
        formats:
            json: true
    exception:
        enabled: true
#        exception_controller: 'App\Controller\ExceptionController::showAction'
        codes:
            'App\Exception\ConflictApiException': 409
            'App\Exception\NotFoundApiException': 404
            'App\Exception\ForbiddenApiException': 403
        messages:
            'App\Exception\ConflictApiException': true
            'App\Exception\NotFoundApiException': true
            'App\Exception\ForbiddenApiException': true

    service:
#        templating: templating
        view_handler: fos_rest.view_handler.default

#        codes:
#            \Exception: 500
#        messages:
#            \Exception: true
    format_listener:
        rules:
            - { path: ^/, prefer_extension: true, fallback_format: json, priorities: [ json, html ] }
